### ISSUE TITLE
improve html style

### ISSUE THREAD

**Issue by b2renger** [b2renger/p5js_codecreatif#4]
no margin
no padding 
no scrollbars

**Comment by b2renger** [comment]
`  <style> * { padding:0; margin:0 }</style>`

**Comment by R4ph3rd** [comment]
readme updated with those few lines 
`  <style> * {padding: 0; margin: 0; overflow-y: hidden; scrollbar-width: none;} 
	  ::-webkit-scrollbar { display: none; } 
  </style>`
Works on Firefox, Brave, Opera and Chrome.
